# Generated by Django 3.2.2 on 2021-06-06 12:17

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='telephone',
            field=models.CharField(max_length=20, validators=[pages.models.phone_number], verbose_name='Номер телефона доктора'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Название статуса'),
        ),
    ]
